apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: gcr.io/golden-sandbox-343808/github.com/arosh-segar/ctse-a2-fastapi
          ports:
            - containerPort: 80
