apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
spec: 
  selector:
    matchLabels:
      app: fastapi-server
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-server
    spec: 
      containers:
        - name: fastapi-server
          image: aroshsegar/fastapi-server:v1
          ports:
            - containerPort: 3000