apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  replicas: 2
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: fastapi-app
          image: gcr.io/golden-sandbox-343808/github.com/arosh-segar/ctse-a2-fastapi
          ports:
            - containerPort: 80
